export const isDev = process.env.NODE_ENV === 'development'

export const API_DEV = 'http://localhost:8080'
export const API_PRO = 'https://console.shipon.de'
export const BASE_URL = isDev ? API_DEV : ''

export const DEFAULT_ERR_MSG = 'Server error'

export const RELOAD = 'RELOAD'

/*  */
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_SESSION = 'GET_SESSION'

/*  */
export const SHOW_CHANGE_PROFILE_MODAL = 'SHOW_CHANGE_PROFILE_MODAL'

export const SHOW_SHIPPING_DETAIL_MODAL = 'SHOW_SHIPPING_DETAIL_MODAL'
export const SHOW_ADD_COMPARE_ITEM_MODAL = 'SHOW_ADD_COMPARE_ITEM_MODAL'
export const HIDE_ADD_COMPARE_ITEM_MODAL = 'HIDE_ADD_COMPARE_ITEM_MODAL'
export const SHOW_PRODUCTLIST_SCHEDULER_TEST_MODAL = 'SHOW_PRODUCTLIST_SCHEDULER_TEST_MODAL'
export const PRODUCTLIST_SCHEDULER_RESULT = 'PRODUCTLIST_SCHEDULER_RESULT'

// seluv
export const GET_ZARA_CATEGORY_LIST = 'GET_ZARA_CATEGORY_LIST'
export const UPDATE_ZARA_CATEGORY = 'UPDATE_ZARA_CATEGORY'
export const START_CATEGORY_UPDATE = 'START_CATEGORY_UPDATE'
export const HIDE_LOADING_ICON = 'HIDE_LOADING_ICON'

// product
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
export const GET_PRODUCT_SHIPPING_DETAIL = 'GET_PRODUCT_SHIPPING_DETAIL'

export const GET_COMPARING_LIST = 'GET_COMPARING_LIST'
export const GET_COMPARING_ITEM = 'GET_COMPARING_ITEM'
export const UPDATE_COMPARING_ITEM_TITLE = 'UPDATE_COMPARING_ITEM_TITLE'
export const REMOVE_COMPARING_ITEM = 'REMOVE_COMPARING_ITEM'
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT'
export const ADD_COMPARING_ITEM = 'ADD_COMPARING_ITEM'

/* EVENT Constants */
export const EVENT = {
  LOGIN_SUCCESS: 'EVENT.LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'EVENT.LOGOUT_SUCCESS',

  NO_SESSION: 'EVENT.NO_SESSION',
  NEED_TO_RELOGIN: 'NEED_TO_RELOGIN'
}

export const CRYPTO_ENC = 'sha256'
